### ISSUE TITLE
Fixed Stars

### ISSUE THREAD

**Issue by gmsgowtham** [triniwiz/nativescript-star-ratings#3]
Is there any option to fix the value of star

**Comment by sean-perkins** [comment]
Can you please explain your issue in a little more depth? You can set the value of the stars.

**Comment by gmsgowtham** [comment]
In Angular2, the value of the stars is still editable by dragging the stars even after fixing the value of the stars. Will you please send a code snippet for fixing the value of the stars?

**Comment by sean-perkins** [comment]
The plugins API does not mention setting a value to be fixed, where a user could not change it anymore. Why not just use star icons to accomplish fixed values? Just swap out the plugins UI with that UI based on some user interaction.

Otherwise, you can try setting the `min` and `max` value to the current value when you set a rating. That may accomplish what you need.

If all else fails, this is an open source project. Feel free to fork, add your functionality and PR it back.

**Comment by gmsgowtham** [comment]
Thank you for your explanation.
